//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Frameworck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diccionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diccionario()
        {
            this.TERMINOS_DICCIONARIOS = new HashSet<TERMINOS_DICCIONARIOS>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string dic_abr { get; set; }
        public Nullable<System.DateTime> FechaIncercion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TERMINOS_DICCIONARIOS> TERMINOS_DICCIONARIOS { get; set; }
    }
}
