//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Frameworck
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpresaContext : DbContext
    {
        public EmpresaContext()
            : base("name=EmpresaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diccionario> Diccionario { get; set; }
        public virtual DbSet<MODULO_USUARIO> MODULO_USUARIO { get; set; }
        public virtual DbSet<MODULOS> MODULOS { get; set; }
        public virtual DbSet<SUBMENU> SUBMENU { get; set; }
        public virtual DbSet<SUBMODULOS> SUBMODULOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TERMINOS_DICCIONARIOS> TERMINOS_DICCIONARIOS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
