//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Frameworck
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODULOS()
        {
            this.MODULO_USUARIO = new HashSet<MODULO_USUARIO>();
            this.SUBMODULOS = new HashSet<SUBMODULOS>();
        }
    
        public int id { get; set; }
        public string NOMBRE_MOD { get; set; }
        public string COD_MOD { get; set; }
        public int SECTOR_MOD { get; set; }
        public Nullable<System.DateTime> FechaIncercion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODULO_USUARIO> MODULO_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBMODULOS> SUBMODULOS { get; set; }
    }
}
