//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Frameworck
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBMODULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBMODULOS()
        {
            this.SUBMENU = new HashSet<SUBMENU>();
        }
    
        public int id { get; set; }
        public string NOMBRE_SUBMOD { get; set; }
        public string SYS_NOM { get; set; }
        public int ID_MODULO { get; set; }
        public Nullable<System.DateTime> FechaIncercion { get; set; }
    
        public virtual MODULOS MODULOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBMENU> SUBMENU { get; set; }
    }
}
